### ISSUE TITLE
[Bug]  error: key value cannot be empty or whitespace (config section: security.root_keys[]): key1

### ISSUE THREAD

**Issue by BinariusConsulting** [ArcadeAI/arcade-mcp#411]
Describe the Bug
Even though I have defined root_keys and private_rsa_keys with values sourced from environment variables in my engine.yaml, the Arcade MCP server still fails to start, giving an error that a key value is empty or whitespace.

How to Reproduce
Steps to reproduce the bug:

Set the following in engine.yaml:
```
security:
  root_keys:
    - id: key1
      default: true
      value: ${env:ROOT_KEY_1}

  private_rsa_keys:
    - id: key1
      default: true
      value: ${env:PRIVATE_RSA_KEY}

```
In your engine.env file, set the following:

```
ROOT_KEY_1=redacted
PRIVATE_RSA_KEY=redacted
```

Run the Arcade MCP server Docker container using the docker-compose.yml.

```
version: "3.8"

services:
  arcade-engine:
    image: ghcr.io/arcadeai/engine:latest
    container_name: arcade_engine
    ports:
      - "9099:9099"
    volumes:
      - ./engine.yaml:/bin/engine.yaml
      - ./engine.env:/bin/engine.env
    env_file:
      - ./engine.env
    restart: unless-stopped
```

Observe the error output in the logs:

```
2025-05-26 22:07:58 arcade_engine  | 2025/05/27 05:07:58 Arcade Engine has finished with error: key value cannot be empty or whitespace (config section: security.root_keys[]): key1
```
Expected Behavior:

The Arcade MCP server should start successfully using the keys provided via environment variables without throwing a configuration error.

![Image](https://github.com/user-attachments/assets/20be15d5-632a-4d12-9d1a-9b402d49c212)
